In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Grocery_data.csv')

In [4]:
df.head()

,Product Name,Category,Quantity,Original Price (Rs.),Discount,Discounted Price (Rs.)
0,"Baby Wipes - Sea Breeze, No Paraben, Double Mo...",Deals of the Week,80 pcs,154.35,47% OFF,105.0
1,New Xtra Large - 7 Diaper Pants,Deals of the Week,7 pcs,149.00,0% off,149.0
2,"Choco Mocha Cold Coffee - Flavoured Milk, Read...",Deals of the Week,180 ml - Tetra Pack,44.40,11% OFF,40.0
3,Intense Coffee & Milk Beverage Flavoured Milk ...,Deals of the Week,180 ml - Can,69.55,7% OFF,65.0
4,"Cheese Slice - Plain, Made from Cow's Milk",Deals of the Week,476 g - (28 Slices),441.35,30% OFF,339.5

In [5]:
df.isnull().sum()

Product Name                 0
Category                     0
Quantity                     0
Original Price (Rs.)      2564
Discount                    38
Discounted Price (Rs.)    2564
dtype: int64

In [6]:
df.describe()

       Original Price (Rs.)  Discounted Price (Rs.)
count          23204.000000            23204.000000
mean             466.401344              368.054982
std             1009.672495              521.500801
min                0.000000                0.000000
25%              127.972250              109.000000
50%              260.725000              212.500000
75%              500.000000              420.000000
max            59750.520000            12822.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25768 entries, 0 to 25767
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Product Name            25768 non-null  object
 1   Category                25768 non-null  object
 2   Quantity                25768 non-null  object
 3   Original Price (Rs.)    23204 non-null  float64
 4   Discount                25730 non-null  object
 5   Discounted Price (Rs.)  23204 non-null  float64
dtypes: float64(2), object(4)
memory usage: 1.2+ MB

In [8]:
# Fill with a constant value
df['Discount'].fillna('0%', inplace=True)

# Fill numeric columns with mean/median
df['Original Price (Rs.)'].fillna(df['Original Price (Rs.)'].mean(), inplace=True)
df['Discounted Price (Rs.)'].fillna(df['Discounted Price (Rs.)'].median(), inplace=True)

# Forward fill (use previous value)
df['Quantity'].fillna(method='ffill', inplace=True)

# Backward fill (use next value)
df['Quantity'].fillna(method='bfill', inplace=True)

C:\Users\Ishita\AppData\Local\Temp\ipykernel_11136\2037396557.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discount'].fillna('0%', inplace=True)
C:\Users\Ishita\AppData\Local\Temp\ipykernel_11136\2037396557.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Original Price (Rs.)'].fillna(df['Original Price (Rs.)'].mean(), inplace=True)
C:\Users\Ishita\AppData\Local\Temp\ipykernel_11136\2037396557.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Discounted Price (Rs.)'].fillna(df['Discounted Price (Rs.)'].median(), inplace=True)
C:\Users\Ishita\AppData\Local\Temp\ipykernel_11136\2037396557.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Quantity'].fillna(method='ffill', inplace=True)
C:\Users\Ishita\AppData\Local\Temp\ipykernel_11136\2037396557.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Quantity'].fillna(method='ffill', inplace=True)
C:\Users\Ishita\AppData\Local\Temp\ipykernel_11136\2037396557.py:12: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Quantity'].fillna(method='bfill', inplace=True)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25768 entries, 0 to 25767
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Product Name            25768 non-null  object
 1   Category                25768 non-null  object
 2   Quantity                25768 non-null  object
 3   Original Price (Rs.)    25768 non-null  float64
 4   Discount                25768 non-null  object
 5   Discounted Price (Rs.)  25768 non-null  float64
dtypes: float64(2), object(4)
memory usage: 1.2+ MB

In [13]:
df.head()

,Product Name,Category,Quantity,Original Price (Rs.),Discount,Discounted Price (Rs.)
0,"Baby Wipes - Sea Breeze, No Paraben, Double Mo...",Deals of the Week,80 pcs,154.35,47% OFF,105.0
1,New Xtra Large - 7 Diaper Pants,Deals of the Week,7 pcs,149.00,0% off,149.0
2,"Choco Mocha Cold Coffee - Flavoured Milk, Read...",Deals of the Week,180 ml - Tetra Pack,44.40,11% OFF,40.0
3,Intense Coffee & Milk Beverage Flavoured Milk ...,Deals of the Week,180 ml - Can,69.55,7% OFF,65.0
4,"Cheese Slice - Plain, Made from Cow's Milk",Deals of the Week,476 g - (28 Slices),441.35,30% OFF,339.5

In [15]:
from sklearn.preprocessing import StandardScaler
import re

# Create a copy of the dataframe to preserve original data
df_standardized = df.copy()

# Extract numeric values from Quantity column
df_standardized['Quantity_Numeric'] = df_standardized['Quantity'].apply(
    lambda x: float(re.findall(r'\d+\.?\d*', str(x))[0]) if re.findall(r'\d+\.?\d*', str(x)) else 0
)

# Select numerical columns to standardize
numerical_cols = ['Original Price (Rs.)', 'Discounted Price (Rs.)', 'Quantity_Numeric']

# Initialize the StandardScaler
scaler = StandardScaler()

# Standardize the numerical columns
df_standardized[numerical_cols] = scaler.fit_transform(df_standardized[numerical_cols])

# Display the standardized data
df_standardized.head()

,Product Name,Category,Quantity,Original Price (Rs.),Discount,Discounted Price (Rs.),Quantity_Numeric
0,"Baby Wipes - Sea Breeze, No Paraben, Double Mo...",Deals of the Week,80 pcs,-0.325697,47% OFF,-0.498091,-0.239117
1,New Xtra Large - 7 Diaper Pants,Deals of the Week,7 pcs,-0.331281,0% off,-0.409569,-0.636647
2,"Choco Mocha Cold Coffee - Flavoured Milk, Read...",Deals of the Week,180 ml - Tetra Pack,-0.440455,11% OFF,-0.628863,0.305445
3,Intense Coffee & Milk Beverage Flavoured Milk ...,Deals of the Week,180 ml - Can,-0.414205,7% OFF,-0.578566,0.305445
4,"Cheese Slice - Plain, Made from Cow's Milk",Deals of the Week,476 g - (28 Slices),-0.026147,30% OFF,-0.026309,1.917348